name: "Build drakpdb distribution packages"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Build source distribution
      run: |
        pip install -U setuptools
        python3 setup.py sdist
    - name: Build wheel distribution
      run: |
        pip install cibuildwheel==2.19.2
        python -m cibuildwheel --output-dir dist --archs x86_64 --platform linux
    - uses: actions/upload-artifact@v4
      with:
        name: drakpdb-wheels
        path: ./dist/*
