name: "Lint and test drakpdb"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CERT-Polska/lint-python-action@v2
        with:
          python-version: 3.8
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install . -r tests/requirements.txt
      - run: pytest
