name: "Make drakpdb distribution"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Build source distribution
      run: python3 setup.py sdist
    - name: Build wheel distribution
      run: |
        pip install cibuildwheel==2.19.2
        python -m cibuildwheel --output-dir dist --archs x86_64 --platform linux
    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels
        path: ./dist/*
